#define CORRIDOR 0
#define SLEEPING_BARBER 1
#define WAKE_BARBER 2
#define BARBER_CHAIR 3
#define END_OF_CUTTING 4
#define WAITING_CLIENTS 5
#define LIMIT_WAITING_CLIENTS 6
#define WAITING_ROOM_QUEUE 7